apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.*"
    helm:
      values: |
        loki:
          auth_enabled: true
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2026-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

          storage:
            type: filesystem
          persistance:
            enabled: true
            size: 10Gi

      singleBinary:
        replicas: 1

      gateway:
        enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



