apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-promtail
  namespace: argocd
spec: 
  project: default
  source:
    repoUrl: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "6.*"
    helm:
      values: |
        config:
          clients:
            - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

        serviceMonitor:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
