apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.*
    helm:
      values: |
        config:
          clients:
            - url: http://loki.monitoring.svc:3100/loki/api/v1/push

          snippets:
            pipelineStages:
              - cri: {}

            # 🔥 HARD LIMIT (REAL FIX): only discover pods in these namespaces
            scrapeConfigs: |
              - job_name: kubernetes-pods-limited
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - plane
                        - student-api
                        - argocd

                relabel_configs:
                  # keep only running pods
                  - action: keep
                    source_labels: [__meta_kubernetes_pod_phase]
                    regex: Running

                  # label basics (optional but nice)
                  - action: replace
                    source_labels: [__meta_kubernetes_namespace]
                    target_label: namespace
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_container_name]
                    target_label: container

                  # point promtail to the container log files
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                    separator: /
                    target_label: __path__
                    replacement: /var/log/pods/*$1/*.log

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

