apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.*
    helm:
      values: |
        config:
          # FULL OVERRIDE so we don't inherit the chart's default "scrape everything"
          file: |
            server:
              http_listen_port: 3101
              grpc_listen_port: 0

            positions:
              filename: /run/promtail/positions.yaml

            clients:
              - url: http://loki.monitoring.svc:3100/loki/api/v1/push

            scrape_configs:
              - job_name: kubernetes-pods-one-namespace
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - plane   # <--- CHANGE THIS to the ONE namespace you want

                pipeline_stages:
                  - cri: {}

                relabel_configs:
                  - action: keep
                    source_labels: [__meta_kubernetes_pod_phase]
                    regex: Running

                  - action: replace
                    source_labels: [__meta_kubernetes_namespace]
                    target_label: namespace
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_container_name]
                    target_label: container

                  # container log path on k8s nodes
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                    separator: /
                    target_label: __path__
                    replacement: /var/log/pods/*$1/*.log
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

