apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiril-shop-wildcard
  namespace: plane
spec:
  secretName: kiril-shop-wildcard-tls
  issuerRef: 
    name: letsencrypt-cloudflare-staging
    kind: ClusterIssuer
  dnsNames:
    - "*.kiril.shop"
    - "kiril.shop"
