apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KirilMilosevski/Plane-GitOps-Kubernetes.git
    targetRevision: main
    path: monitoring

    directory:
      recurse: true

  destionation:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
